properties:
  run:
    type: string
  build:
    type: [ string, array ]
    minimum: 1
  push:
    type: [ string, array ]
    minimum: 1
  pull:
    type: [ string, array ]
    minimum: 1
  config:
    type: [ string, array ]
    minimum: 1
  env:
    type: [ string, array ]
    minimum: 1
  environment:
    type: [ string, array ]
    minimum: 1
  image-repository:
    type: string
  image-name:
    type: string
  pull-retries:
    type: integer
  push-retries:
    type: integer
  shell:
    type: string
  cache-from:
    type: [ string, array ]
    minimum: 1
  leave-volumes:
    type: boolean
  no-cache:
    type: boolean
  tty:
    type: boolean
  dependencies:
    type: boolean
  verbose:
    type: boolean
oneOf:
  - required:
      - run
  - required:
      - build
  - required:
      - push
additionalProperties: false
dependencies:
  pull: [ run ]
  image-repository: [ build ]
  image-name: [ build ]
  env: [ run ]
  environment: [ run ]
  pull-retries: [ build, run ]
  push-retries: [ push ]
  cache-from: [ build ]
  leave-volumes: [ run ]
  no-cache: [ build ]
  dependencies: [ run ]
  tty: [ run ]
